version: '3.4'
services:
  node:
    tty: true
    stdin_open: true
    container_name: users-microservice
    env_file:
      - ./.env
    depends_on:
      - mongo
    build:
      context: .
      target: deps
      args:
        - NPM_TOKEN
    ports:
      - '5050:4040'
    volumes:
      - '.:/var/code:rw'
    entrypoint: ./startup.sh
  mongo:
    image: 'mongo:latest'
